### ISSUE TITLE
Linux Kitの検証

### ISSUE THREAD

**Issue by ugwis** [kstm-su/ztp#1]
## WHY
Linux Kitを使ってブート可能なISOイメージを生成するため、どんな動作環境が必要なのか検証する

## WHAT
- [x] LinuxKitでブートしてみる
- [x] 仮想化支援が必要かどうか
- [x] PXE BOOTで配布実験

**Comment by bgpat** [comment]
64bitじゃないとうごかないっぽい (ESXi 32bit)

**Comment by bgpat** [comment]
サークル部屋のサーバー(64bit 仮想化支援なし)で ~起動せず~ -> と思ったら起動した

**Comment by bgpat** [comment]
ESXi上のサーバーだとPXEでも起動可

**Comment by ugwis** [comment]
Linux Kit自体はうまく動いているようだけどttyとかがどういうふうに繋がっているよくわからない。。。

linuxkit/gettyのコンテナを動かすとそのシェルっぽいのが立ち上がるのはわかった
https://github.com/linuxkit/linuxkit/blob/master/examples/getty.yml

nginxも動くのを確認したけど、dhcpcdがうまくIPを取得できなくてローカルからしか動いてるのを確認できなかった

**Comment by ugwis** [comment]
とりあえず今の所仮想化支援はなくても大丈夫、64bitじゃないとうまく動かないよう

PXEでもブートは出来てるので想定していることは出来そう

**Comment by bgpat** [comment]
使うカーネル変えれば32bitでも動くかも？

**Comment by bgpat** [comment]
DHCPベースならOpenFlowでネットワーク制御できるようにしちゃうのもありかも

**Comment by ugwis** [comment]
> DHCPベースならOpenFlowでネットワーク制御できるようにしちゃうのもありかも

プロビジョニング用のネットワーク、稼働用のネットワークをOpenFlowで切り替えるってことですか
