### ISSUE TITLE
待機用イメージを作る

### ISSUE THREAD

**Issue by bgpat** [kstm-su/ztp#14]
## WHY

MACアドレスを調べてWebUIで登録しないといけない

## WHAT

面倒なのでWPS的なフローで登録できるようにしたい

**Comment by ugwis** [comment]
- [x] DHCPのリクエストが来ると待機用イメージを返す
- [x] 待機用イメージがManagerのPOST:/nodesを叩いてMacアドレスを登録する
- [ ] 待機用イメージの中でhttpサーバを立てて、Manager側でイメージを選択するとエンドポイントを叩いて再起動する

**Comment by bgpat** [comment]
> 待機用イメージがManagerのPOST:/nodesを叩いてMacアドレスを登録する

`POST` じゃなくて `PUT` です

**Comment by ugwis** [comment]
あ、先にノード登録してMACアドレス追記するんでしたっけ？
その場合登録したノードと実際に接続するノードと紐付けができない気がする...

**Comment by bgpat** [comment]
> あ、先にノード登録してMACアドレス追記するんでしたっけ？
> その場合登録したノードと実際に接続するノードと紐付けができない気がする...

あ、ごめんなさいあってました

**Comment by bgpat** [comment]
ref: https://github.com/kstm-su/ztp/pull/31

**Comment by ugwis** [comment]
待機用イメージに関して、毎回立ち上げ時にLinuxKitのビルドめんどくさいよねという話があったんですが、今のやり方だとビルド時にDHCPサーバのIPを環境変数に埋め込んでいるのでイメージファイルをGitHub Releaseみたいなところにあげるのは難しそうです。
環境変数以外の方法でDHCPサーバのIPを見つけるか、毎回起動時にビルドするかどっちかになるのかなという感じです。

環境変数以外の方法だとDHCPクライアントをのログからIPを見つけるとか、前やってたDHCP Discoverでサーバを見つけるとかが思いつくんですが他にいい方法ありますか？

**Comment by bgpat** [comment]
DHCP Discover でやるなら使えるのは next server でしょうか。(TFTPサーバーのIPアドレスがわかる)
毎回ビルドは効率悪いし見た目もよくないのでやめたいです。

**Comment by bgpat** [comment]
DHCP Request で登録までしちゃうのもアリかもしれない

**Comment by ugwis** [comment]
next serverでもいいですね（DHCPのIPよりTFTPのIPの方が良さそう)

> DHCP Request で登録までしちゃうのもアリかもしれない

LinuxKitに入ってるDHCPクライアントを置き換えるってことですか？

**Comment by bgpat** [comment]
> LinuxKitに入ってるDHCPクライアントを置き換えるってことですか？

そのまま使ってもいいような気がします
