### ISSUE TITLE
Agent/Masterの仕様

### ISSUE THREAD

**Issue by ugwis** [kstm-su/ztp#2]
## WHY
AgentとWebUIをどういう仕様にするかざっくり決め始める

## WHAT
- [ ] なんのプロトコルを使って通信するか
- [ ] DHCP,TFTPサーバ　（コンテナを使うか？独自実装するか？）

**Comment by ugwis** [comment]
それぞれのノードのIPアドレスをWeb UIから割振れるとして、その場合ってDHCPサーバは自分で実装したほうが楽なのかしら

**Comment by bgpat** [comment]
実装始めちゃったので閉じちゃう
