### ISSUE TITLE
デモ用の設定を作る

### ISSUE THREAD

**Issue by bgpat** [kstm-su/ztp#22]
## WHY

ミニプロコンでデモで見栄えのいいイメージを使いたい

## WHAT

LinuxKitの設定を書く
自分たちで書いたサーバーなんかが動くといい

**Comment by ugwis** [comment]
## 狙い
・簡単にプロビジョニングできていることを示したい
・並列に動作させることによってサーバー資源を有効に活用できているように示したい

**Comment by ugwis** [comment]
## 案1: 自分のプライベートIPを返すWebサーバーを立てて、ラウンドロビンさせる
メリット:
- 実装むっちゃ楽

デメリット:
- 味気ない？

**Comment by ugwis** [comment]
## 案2: 簡易エージェントを作って、モニタリングする
メリット: 
- 実際にノードが動いていることがわかりやすい
- 今後のエージェント作成に繋がる

デメリット:
- どの程度まで作り込むかによってかかる時間が変わる
