### ISSUE TITLE
[WIP] Web UIの作成

### ISSUE THREAD

**Issue by ugwis** [kstm-su/ztp#4]
## WHY
コマンドラインから管理するの厳しい

## WHAT
必要な機能
- [ ] configファイルからISOイメージ作成(storageに生成)
- [ ] 対象のコンピュータ(MACアドレス)で起動する イメージを選択し、dhcpサーバ(@bgpat)へPXEブートのルールを送信する

なんとなくpolymer.jsで作り始めた 1af82731714fff390879b37f2ec574fb01ac9892

**Comment by bgpat** [comment]
> 対象のコンピュータ(MACアドレス)で起動する イメージを選択し、dhcpサーバ(@bgpat)へPXEブートのルールを送信する

ちょうどそれっぽいのができた https://github.com/bgpat/dhcpd
